### ISSUE TITLE
how to center text ?

### ISSUE THREAD

**Issue by xgz123** [crackcomm/go-clitable#5]
how to align center ?
thanks

**Comment by crackcomm** [comment]
@xgz123 I didn't get a notification for this issue or I missed it.

This is not implemented but you can center strings in [`fieldString`](https://github.com/crackcomm/go-clitable/blob/master/table.go#L165) method.

**Comment by xgz123** [comment]
I have two idea in mind of how to implement it.
```
// 1
table.CenterColumn(cols ...string)
table.Print()
// 2
table.PrintCenter(cols ...string)
```
which one do you think is better ?

**Comment by crackcomm** [comment]
How about adding option to `Table` struct?

like so:
```Go
type Table struct {
    // ...
    CenterText bool
    // ...
}
```

**Comment by xgz123** [comment]
> How about adding option to `Table` struct?
> 
> like so:
> 
> ```go
> type Table struct {
>     // ...
>     CenterText bool
>     // ...
> }
> ```

This is a table level config while I only need some of the columns to be centered.

**Comment by crackcomm** [comment]
That's interesting.

In this case maybe

```Go
type Table struct {
    // ...
    CenterText map[string]bool
    // ...
}
```
